Bài tập 1. Viết chương trình NumPy để tạo phép so sánh theo từng phần tử (lớn hơn, lớn hơn_bằng, ít hơn và nhỏ hơn_bằng nhau) của hai mảng đã cho.

In [4]:
import numpy as np
mang1 = np.array([1, 2, 3, 4, 5])
mang2 = np.array([5, 4, 3, 2, 1])

lon_hon_ket_qua = np.greater(mang1, mang2)
print("Lớn hơn:", lon_hon_ket_qua)
lon_hon_bang_ket_qua = np.greater_equal(mang1, mang2)
print("Lớn hơn bằng:", lon_hon_bang_ket_qua)

it_hon_ket_qua = np.less(mang1, mang2)
print("Ít hơn:", it_hon_ket_qua)
it_hon_bang_ket_qua = np.less_equal(mang1, mang2)
print("Ít hơn bằng:", it_hon_bang_ket_qua)


Lớn hơn: [False False False  True  True]
Lớn hơn bằng: [False False  True  True  True]
Ít hơn: [ True  True False False False]
Ít hơn bằng: [ True  True  True False False]


Bài tập 2: Viết chương trình NumPy để tạo một mảng các số nguyên từ 30 đến 70

In [5]:
import numpy as np
my_array = np.arange(30, 70)

print(my_array)


[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69]


Bài tập 3: Viết chương trình NumPy để tạo ma trận nhận đơn vị 3x3

In [6]:
import numpy as np
identity_matrix = np.eye(3)

print("Ma trận nhận đơn vị 3x3:")
print(identity_matrix)


Ma trận nhận đơn vị 3x3:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Bài tập 4: Viết chương trình NumPy để tạo ma trận 4x4 trong đó 0 và 1 được đặt so le, với các số 0 trên đường chéo chính.
[[ 0.  1.  0.  1.]
 [ 1.  0.  1.  0.]
 [ 0.  1.  0.  1.]
 [ 1.  0.  1.  0.]]  

In [7]:
import numpy as np
matrix = np.zeros((4, 4))
matrix[::2, 1::2] = 1 
matrix[1::2, ::2] = 1 

print(matrix)


[[0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]]


Bài tập 5: Viết chương trình NumPy để thêm một vectơ vào mỗi hàng của một ma trận đã cho

In [9]:
import numpy as np

ma_tran = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
vector_cong = np.array([10, 11, 12])
ket_qua_ma_tran = ma_tran + vector_cong

print("Ma trận gốc:")
print(ma_tran)
print("\nVector cần cộng:")
print(vector_cong)
print("\nKết quả ma trận sau khi thêm vector vào mỗi hàng:")
print(ket_qua_ma_tran)


Ma trận gốc:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Vector cần cộng:
[10 11 12]

Kết quả ma trận sau khi thêm vector vào mỗi hàng:
[[11 13 15]
 [14 16 18]
 [17 19 21]]
