Bài tập 1: Viết chương trình NumPy để trích xuất tất cả các số từ một mảng đã cho nhỏ hơn một số đã chỉ định

In [3]:
import numpy as np
def trich_xuat_so_nho_hon_nguong(arr, nguong):
    ket_qua = arr[arr < nguong]
    return ket_qua
mang_input = np.array([1, 5, 8, 10, 3, 6, 12, 7])
gia_tri_nguong = 8
mang_ket_qua = trich_xuat_so_nho_hon_nguong(mang_input, gia_tri_nguong)
print("Các số nhỏ hơn {} là: {}".format(gia_tri_nguong, mang_ket_qua))


Các số nhỏ hơn 8 là: [1 5 3 6 7]


Bài tập 2: Viết chương trình NumPy để thay thế tất cả các số trong một mảng đã cho lớn hơn một số đã cho trước thành số đó.

In [2]:
import numpy as np
def thay_the_lon_hon(arr, nguong, so_thay_the):
    return np.where(arr > nguong, so_thay_the, arr)
mang_dau_vao = np.array([1, 5, 10, 15, 20])
nguong_gia_tri = 15
so_thay_the_gia_tri = 995
mang_ket_qua = thay_the_lon_hon(mang_dau_vao, nguong_gia_tri, so_thay_the_gia_tri)
print("Mảng đầu vào:", mang_dau_vao)
print("Ngưỡng:", nguong_gia_tri)
print("Số thay thế:", so_thay_the_gia_tri)
print("Mảng sau khi thay thế:", mang_ket_qua)


Mảng đầu vào: [ 1  5 10 15 20]
Ngưỡng: 15
Số thay thế: 995
Mảng sau khi thay thế: [  1   5  10  15 995]


Bài tập 3: Viết chương trình NumPy để tạo một mảng 4x4, sau đó hãy tạo một mảng mới từ mảng đã tạo ở trên bằng cách hoán đổi cột đầu tiên và cuối cùng, cột thứ hai và cột thứ ba

In [3]:
import numpy as np
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])
print("Mảng gốc:")
print(arr)
arr[:, [0, 3, 1, 2]] = arr[:, [3, 0, 2, 1]]
print("\nMảng sau khi hoán đổi cột:")
print(arr)


Mảng gốc:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Mảng sau khi hoán đổi cột:
[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]


Bài tập 4: Viết chương trình NumPy để hoán đổi các hàng và cột của một mảng đã cho theo thứ tự ngược lại

In [6]:
import numpy as np
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
arrhangnguoc = arr[::-1, :]
arrcotnguoc = arr[:, ::-1]
print("Mảng ban đầu:\n", arr)
print("Mảng sau khi hoán đổi các hàng:\n", arrhangnguoc)
print("Mảng sau khi hoán đổi các cột:\n", arrcotnguoc)


Mảng ban đầu:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Mảng sau khi hoán đổi các hàng:
 [[7 8 9]
 [4 5 6]
 [1 2 3]]
Mảng sau khi hoán đổi các cột:
 [[3 2 1]
 [6 5 4]
 [9 8 7]]


Bài tập 5: Viết chương trình NumPy để nhân hai mảng đã cho có cùng kích thước theo từng phần tử

In [7]:
import numpy as np
arr1= np.array([1,2,3])
arr2= np.array([4,5,6])
result= arr1*arr2
print ("mảng 1",arr1)
print ("mảng 2",arr2)
print ("kết quả phép nhân của hai mang đã cho cùng kích thước phần tử",result)


mảng 1 [1 2 3]
mảng 2 [4 5 6]
kết quả phép nhân của hai mang đã cho cùng kích thước phần tử [ 4 10 18]
