Bài tập 1: Viết chương trình Python thực hiện các thao tác sau:
1. Nhập 2 số nguyên dương m, n từ bàn phím. 
2. Tạo ra một mảng 2 chiều A kích thước mxn trong đó giá trị phần tử trong hàng thứ i và cột thứ j của mảng phải là i+j+i*j; i=0,1,...,m-1; j=0,1,...,n-1
3. Tính tổng của các phần tử theo hàng, theo cột, toàn bộ giá trị trong mảng A.
4. Tạo ra một mảng 2 chiều B kích thước mxn trong đó giá trị các phần tử trong mảng là các số thực được chọn ngẫu nhiên từ -10 đến 10
5. Tìm giá trị lớn nhất của các phần tử theo hàng, theo cột ở trong mảng B
6. Tạo mảng C trong đó mỗi phần tử của mảng C là tổng của các phần tử tương ứng trong 2 mảng A, B.
7. Tạo mảng D trong đó:
- Phần tử ở hàng lẻ bằng hiệu của các phần tử tương ứng trong 2 mảng A, B
- Phần tử ở hàng chẵn bằng tích của các phần tử tương ứng trong 2 mảng A, B 

In [1]:
import numpy as np
m = int(input("Nhập giá trị cho m: "))
n = int(input("Nhập giá trị cho n: "))

A = np.array([[i + j + i * j for j in range(n)] for i in range(m)])
tong_theo_hang_A = np.sum(A, axis=1)
tong_theo_cot_A = np.sum(A, axis=0)
tong_toan_bo_A = np.sum(A)
B = np.random.uniform(-10, 10, (m, n))
max_theo_hang_B = np.max(B, axis=1)
max_theo_cot_B = np.max(B, axis=0)
max_toan_bo_B = np.max(B)

C = A + B
D = np.zeros_like(A, dtype=float)
D[1::2, :] = A[1::2, :] - B[1::2, :]
D[::2, :] = A[::2, :] * B[::2, :]
print("Mảng A:")
print(A)

print("\nTổng theo hàng của A:")
print(tong_theo_hang_A)

print("\nTổng theo cột của A:")
print(tong_theo_cot_A)

print("\nTổng toàn bộ giá trị của A:")
print(tong_toan_bo_A)

print("\nMảng B:")
print(B)

print("\nGiá trị lớn nhất theo hàng của B:")
print(max_theo_hang_B)

print("\nGiá trị lớn nhất theo cột của B:")
print(max_theo_cot_B)

print("\nGiá trị lớn nhất toàn bộ của B:")
print(max_toan_bo_B)

print("\nMảng C (tổng của A và B):")
print(C)

print("\nMảng D:")
print(D)


Nhập giá trị cho m: 3
Nhập giá trị cho n: 5
Mảng A:
[[ 0  1  2  3  4]
 [ 1  3  5  7  9]
 [ 2  5  8 11 14]]

Tổng theo hàng của A:
[10 25 40]

Tổng theo cột của A:
[ 3  9 15 21 27]

Tổng toàn bộ giá trị của A:
75

Mảng B:
[[ 8.2080783  -8.04992458 -4.67922158 -0.79380543 -3.71430774]
 [ 5.5067225   2.29458796  4.68276503 -6.76747996  7.04562909]
 [ 7.45149435 -6.23165662  8.35276087  1.10016989  0.54284106]]

Giá trị lớn nhất theo hàng của B:
[8.2080783  7.04562909 8.35276087]

Giá trị lớn nhất theo cột của B:
[8.2080783  2.29458796 8.35276087 1.10016989 7.04562909]

Giá trị lớn nhất toàn bộ của B:
8.352760874323138

Mảng C (tổng của A và B):
[[ 8.2080783  -7.04992458 -2.67922158  2.20619457  0.28569226]
 [ 6.5067225   5.29458796  9.68276503  0.23252004 16.04562909]
 [ 9.45149435 -1.23165662 16.35276087 12.10016989 14.54284106]]

Mảng D:
[[  0.          -8.04992458  -9.35844316  -2.38141628 -14.85723095]
 [ -4.5067225    0.70541204   0.31723497  13.76747996   1.95437091]
 [ 14.9029887  